image: node:12.11

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - cp file index.d.ts node_modules/tesseract.js/src/
    - ls
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages